### ISSUE TITLE
Final data in the same folder

### ISSUE THREAD

**Issue by hjohns12** [PrincetonUniversity/PEC-map#3]
@Michael-Hallee when you create final-ish versions of `state_moneyball_lower.geojson` and `state_moneyball_upper.geojson`, can you put them in the `out-files` folder? Can you store intermediate data in the `data` folder?

**Comment by mike-iezzi** [comment]
Should be good now.  Let me know if anything in the merge is poorly placed

**Comment by hjohns12** [comment]
Looks great. Thanks!
