### ISSUE TITLE
Multi-Layer Merge

### ISSUE THREAD

**Issue by mike-iezzi** [PrincetonUniversity/PEC-map#5]
Can the multi-layer branch be merged with master yet?

If not which branch should I work on integrating the moneyball layers/ playing with styling?

**Comment by mike-iezzi** [comment]
I merged your multi-layer branch with master in the new branch money-multi.

Everything appears to be working well, and I have the new layers added with styling and layer switching.

**Comment by hjohns12** [comment]
I think this already happened, and everything seems to be working well for me. There was one line I found in `styles.css` that didn't get carried over, just added it back into the stylesheet.
